version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 0
  versioning-strategy: widen
#   ignore:
#   - dependency-name: faunadb
#     versions:
#     - 4.0.3
#     - 4.1.1
