backend:
  name: git-gateway
  # Branch to update (optional; defaults to master)
  branch: master

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Id",
          name: "id",
          widget: "string",
          hint: "use for Gitalk id",
          required: false,
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "yyyy/mm/dd/title",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Header Image",
          name: "headerImage",
          hint: "Default: https://i.imgur.com/QmIHfeR.jpg",
          widget: "string",
          default: "https://i.imgur.com/QmIHfeR.jpg" }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "string",
          default: "blog-post",
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown" ,
          default: "## Table of Contents\n\n```toc\n\n```\n",
        }
