name: common lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ⬇️ lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
          args: '*.md .github/**/*.md' # Only Project Description Markdown
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🧼 lint renovate config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
        with:
          config_file_path: 'renovate.json'
