name: DeployToNetlifyPRD
on:
  push:
    branches:
      - master
    paths:
      - src/**
env:
  cache-version: v2

jobs:
  ping-google-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: send sitemap
        run: |
          curl -X GET "http://www.google.com/ping?sitemap=https://blog.tubone-project24.xyz/sitemap-index.xml"
          curl -X GET "http://www.google.com/ping?sitemap=https://blog.tubone-project24.xyz/rss.xml"
          curl -X GET "http://www.google.com/ping?sitemap=https%3A%2F%2Ftubone-project24.xyz%2Findex.php%3Fxml_sitemap%3Dparams%3D"
          curl -X GET "http://www.google.com/ping?sitemap=https://tubone-project24.xyz/index.php/feed/"
